//! The export's audio, streamed: a range export pays for its range, not for
//! the timeline, and reading a file in pieces gives the samples one read
//! gives.
//!
//! This binary counts every allocation (a global allocator that tracks the
//! peak), which is why it is a file of its own: the bound is a property of
//! the process, and other tests in the same binary would move it.
//!
//! Fixtures are generated by FFmpeg into the test's scratch directory; without
//! ffmpeg on PATH the tests say so and skip.

use std::alloc::{GlobalAlloc, Layout, System};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};

use chukcut_engine::modules::audio::decode::FileAudioSource;
use chukcut_engine::modules::export::audio::{frames_for, BLOCK_FRAMES};
use chukcut_engine::modules::export::presets::{AudioCodec, Container};
use chukcut_engine::modules::export::{
    job, resolve_settings, run_export, AudioRequest, AudioSource, ExportJob, ExportOverrides,
    ExportRequest, FnSink, MixRange, MixStream,
};
use chukcut_engine::modules::media::MediaSourceProvider;
use chukcut_engine::modules::project::document::{
    AudioMaterial, CanvasConfig, Micros, Project, Segment, TimeRange, Track, TrackKind, Transform,
    MICROS_PER_SECOND,
};
use chukcut_engine::modules::render::{Compositor, CompositorConfig, SourceProvider};

const S: Micros = MICROS_PER_SECOND;
const HOUR: Micros = 3_600 * S;

// ---------------------------------------------------------------------------
// Counting allocations
// ---------------------------------------------------------------------------

struct Counting;

static LIVE: AtomicUsize = AtomicUsize::new(0);
static PEAK: AtomicUsize = AtomicUsize::new(0);

unsafe impl GlobalAlloc for Counting {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        let ptr = unsafe { System.alloc(layout) };
        if !ptr.is_null() {
            let live = LIVE.fetch_add(layout.size(), Ordering::Relaxed) + layout.size();
            PEAK.fetch_max(live, Ordering::Relaxed);
        }
        ptr
    }

    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        unsafe { System.dealloc(ptr, layout) };
        LIVE.fetch_sub(layout.size(), Ordering::Relaxed);
    }

    unsafe fn realloc(&self, ptr: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
        let out = unsafe { System.realloc(ptr, layout, new_size) };
        if !out.is_null() {
            if new_size >= layout.size() {
                let grow = new_size - layout.size();
                let live = LIVE.fetch_add(grow, Ordering::Relaxed) + grow;
                PEAK.fetch_max(live, Ordering::Relaxed);
            } else {
                LIVE.fetch_sub(layout.size() - new_size, Ordering::Relaxed);
            }
        }
        out
    }
}

#[global_allocator]
static ALLOCATOR: Counting = Counting;

/// The tests measure one process-wide peak, so they take turns.
static SERIAL: Mutex<()> = Mutex::new(());

/// Bytes allocated at the peak of `work`, above what was live before it.
fn peak_during<T>(work: impl FnOnce() -> T) -> (T, usize) {
    let before = LIVE.load(Ordering::Relaxed);
    PEAK.store(before, Ordering::Relaxed);
    let out = work();
    (out, PEAK.load(Ordering::Relaxed).saturating_sub(before))
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

fn scratch() -> PathBuf {
    let dir = Path::new(env!("CARGO_TARGET_TMPDIR")).join("export_audio_stream");
    std::fs::create_dir_all(&dir).expect("create the scratch directory");
    dir
}

/// Keep rendered audio out of the user's own `~/.cache`.
fn private_cache() {
    std::env::set_var("XDG_CACHE_HOME", scratch().join("cache"));
}

/// Two tones at 44.1 kHz in AAC: a lossy codec with priming and overlap, and
/// a rate the 48 kHz mix has to resample — both the reader's state that a
/// careless piece-wise read would get wrong.
fn tones(seconds: u32) -> Option<PathBuf> {
    let path = scratch().join(format!("tones-{seconds}s.m4a"));
    if path.is_file() {
        return Some(path);
    }
    let part = scratch().join(format!("tones-{seconds}s.part.m4a"));
    let ok = Command::new("ffmpeg")
        .args(["-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i"])
        .arg(format!(
            "aevalsrc=0.3*sin(2*PI*220*t)+0.2*sin(2*PI*1330*t)|0.25*sin(2*PI*330*t):s=44100:d={seconds}"
        ))
        .args(["-c:a", "aac", "-b:a", "96k"])
        .arg(&part)
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if !ok {
        eprintln!("skipping: ffmpeg cannot make the fixture");
        return None;
    }
    std::fs::rename(&part, &path).ok()?;
    Some(path)
}

fn segment(id: &str, target: TimeRange, source: TimeRange) -> Segment {
    Segment {
        id: id.into(),
        material_id: "tones".into(),
        target_range: target,
        source_range: source,
        render_index: 0,
        speed: 1.0,
        volume: 1.0,
        transform: Transform::default(),
        crop: None,
        extras: Vec::new(),
        keyframes: Vec::new(),
    }
}

/// Three hours of timeline: the tones at the start, at the end and once in
/// the middle at a tape-speed change.
fn three_hours(path: &Path, clip: Micros) -> Project {
    let mut project = Project::new(
        "long",
        CanvasConfig {
            width: 160,
            height: 90,
            background: [0.0, 0.0, 0.0, 1.0],
        },
        30.0,
    );
    project.materials.audios.push(AudioMaterial {
        id: "tones".into(),
        path: path.to_string_lossy().into_owned(),
        duration: clip,
        sample_rate: 44_100,
        channels: 2,
    });
    let mut lane = Track::new(TrackKind::Audio, "A1");
    lane.segments.push(segment(
        "first",
        TimeRange::new(0, clip),
        TimeRange::new(0, clip),
    ));
    let mut middle = segment(
        "middle",
        TimeRange::new(HOUR, clip / 2),
        TimeRange::new(0, clip),
    );
    middle.speed = 2.0;
    lane.segments.push(middle);
    lane.segments.push(segment(
        "last",
        TimeRange::new(3 * HOUR - clip, clip),
        TimeRange::new(0, clip),
    ));
    project.tracks.push(lane);
    project
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// The file reader's stream, read in pieces of every awkward size and from a
/// later start, gives exactly the samples one read of the whole request
/// gives. The streamed mix is bit-identical to the buffered one only because
/// of this.
#[test]
fn reading_a_file_in_pieces_is_the_same_samples_as_one_read() {
    let _turn = SERIAL.lock().unwrap_or_else(|e| e.into_inner());
    let Some(path) = tones(12) else { return };
    let path = path.to_string_lossy().into_owned();
    for (start, duration) in [(0, 10 * S), (3_456_789, 6 * S)] {
        let request = AudioRequest {
            material_id: "tones",
            path: &path,
            start,
            duration,
            sample_rate: 48_000,
            channels: 2,
        };
        let whole = FileAudioSource.samples(&request).expect("decode");
        assert!(whole.iter().any(|s| s.abs() > 0.1), "the tones are heard");
        for piece in [1_000usize, 4_801, BLOCK_FRAMES] {
            let mut stream = FileAudioSource.stream(&request).expect("open");
            let mut read = Vec::new();
            let mut at = 0;
            while at * 2 < whole.len() {
                let n = piece.min(whole.len() / 2 - at);
                let mut out = vec![0.0; n * 2];
                stream.read(at, &mut out).expect("read");
                read.extend_from_slice(&out);
                at += n;
            }
            assert!(
                read == whole,
                "pieces of {piece} from {start}: the stream differs from one read"
            );
        }
        // A read that starts later decodes through the gap and lands on the
        // same samples as the slice of the whole read.
        let mut stream = FileAudioSource.stream(&request).expect("open");
        let skip = 100_003;
        let mut out = vec![0.0; 20_000 * 2];
        stream.read(skip, &mut out).expect("read");
        assert!(out[..] == whole[skip * 2..(skip + 20_000) * 2]);
    }
}

/// The audit's measurement: a two-second export of a three-hour timeline
/// reached 6.6 GB before the memory guard killed it, because the mix was one
/// buffer the length of the project. Mixed over the range it stays small —
/// the bound here is generous for the decoders and still 50 times under one
/// hour of buffered mix (1.4 GB).
#[test]
fn a_short_range_of_a_three_hour_timeline_stays_small() {
    let _turn = SERIAL.lock().unwrap_or_else(|e| e.into_inner());
    private_cache();
    let Some(path) = tones(12) else { return };
    let project = three_hours(&path, 10 * S);
    assert_eq!(project.duration(), 3 * HOUR);
    const BOUND: usize = 64 << 20;
    let cancel = AtomicBool::new(false);

    // Each range: the start, the speed-changed clip in the middle, the end.
    for (start, length) in [(0, 2 * S), (HOUR + S, 2 * S), (3 * HOUR - 3 * S, 2 * S)] {
        let range = MixRange::export(&project, 48_000, start, length);
        let (mixed, peak) = peak_during(|| {
            MixStream::new(&project, &FileAudioSource, 48_000, 2, range, &cancel)
                .expect("mix")
                .collect()
                .expect("mix")
        });
        assert_eq!(mixed.len(), frames_for(length, 48_000) * 2);
        assert!(
            mixed.iter().any(|s| s.abs() > 0.1),
            "the clip under {start} is heard"
        );
        assert!(
            peak < BOUND,
            "mixing 2 s at {start} of 3 h allocated {} MB at its peak",
            peak >> 20
        );
    }

    // And the whole timeline streamed block by block: the memory is a block,
    // not three hours (4.1 GB buffered).
    let range = MixRange::whole(&project, 48_000);
    let ((), peak) = peak_during(|| {
        let mut stream =
            MixStream::new(&project, &FileAudioSource, 48_000, 2, range, &cancel).expect("mix");
        let mut block = Vec::new();
        let mut frames = 0usize;
        let mut heard = false;
        while stream
            .next_block(BLOCK_FRAMES * 8, &mut block)
            .expect("mix")
        {
            frames += block.len() / 2;
            heard |= block.iter().any(|s| s.abs() > 0.1);
        }
        assert_eq!(frames, range.frames);
        assert!(heard);
    });
    assert!(
        peak < BOUND,
        "streaming 3 h allocated {} MB at its peak",
        peak >> 20
    );
}

/// The same bound through the real export: a sound-only range export of the
/// three-hour timeline, written to a file.
#[test]
fn a_range_export_of_a_three_hour_timeline_stays_small() {
    let _turn = SERIAL.lock().unwrap_or_else(|e| e.into_inner());
    private_cache();
    let Some(path) = tones(12) else { return };
    let Some(ctx) = chukcut_engine::modules::gpu::render_context() else {
        eprintln!("skipping: no GPU adapter on this machine");
        return;
    };
    let project = three_hours(&path, 10 * S);
    let output = scratch().join("range.wav");
    let _ = std::fs::remove_file(&output);
    let request = ExportRequest {
        output_path: output.to_string_lossy().into_owned(),
        preset_id: None,
        overrides: Some(ExportOverrides {
            container: Some(Container::Wav),
            audio_codec: Some(AudioCodec::Pcm),
            ..Default::default()
        }),
        hardware: None,
        include_audio: true,
        range: Some((0, 2 * S)),
    };
    let settings = resolve_settings(&project, &request).expect("settings");
    let compositor = Arc::new(Compositor::with_config(
        ctx,
        CompositorConfig {
            strict_sources: true,
            ..Default::default()
        },
    ));
    let sources: Arc<dyn SourceProvider> = Arc::new(MediaSourceProvider::from_project(&project));
    let job = ExportJob {
        job_id: "range".into(),
        project: project.clone(),
        settings,
        compositor,
        sources,
        audio: job::audio_source(),
        cancel: Arc::new(AtomicBool::new(false)),
    };
    let (outcome, peak) = peak_during(|| run_export(&job, &FnSink(|_| {})));
    let outcome = outcome.expect("the export finishes");
    assert!(!outcome.cancelled);
    assert!(
        peak < 64 << 20,
        "a 2 s export of 3 h allocated {} MB at its peak",
        peak >> 20
    );
    // About 2 s of 48 kHz stereo PCM: the range, not the timeline.
    let size = std::fs::metadata(&output).expect("the file").len();
    assert!(
        (300_000..1_000_000).contains(&size),
        "the WAV is {size} bytes"
    );
}
