//! The shortcut table in `docs/manual/shortcuts.md` is generated from the
//! keymap registry. This test fails when the two disagree, so a new action or
//! a changed default key cannot ship with a stale manual.
//!
//! To rewrite the table after a registry change:
//!
//! ```bash
//! CHUKCUT_BLESS=1 cargo test -p chukcut-engine --test keymap_doc
//! ```

use std::path::PathBuf;

use chukcut_engine::modules::keymap::{keys, Preset, ACTIONS, GROUPS};

const BEGIN: &str = "<!-- keymap-table:begin (generated by crates/engine/tests/keymap_doc.rs) -->";
const END: &str = "<!-- keymap-table:end -->";

fn manual() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../docs/manual/shortcuts.md")
}

/// One preset's keys for an action, as the shortcuts sheet shows them.
fn cell(keys_of_action: &[&str]) -> String {
    if keys_of_action.is_empty() {
        return "(none)".to_string();
    }
    keys_of_action
        .iter()
        .map(|k| {
            let canonical = keys::normalize(k).unwrap_or_else(|_| (*k).to_string());
            format!("`{}`", keys::display(&canonical))
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// The table, group by group, in registry order.
fn table() -> String {
    let mut out = String::new();
    out.push_str(BEGIN);
    out.push('\n');
    for group in GROUPS {
        out.push_str(&format!("\n### {group}\n\n"));
        out.push_str(&format!(
            "| Action | {} | {} | {} |\n|---|---|---|---|\n",
            Preset::Chukcut.label(),
            Preset::Capcut.label(),
            Preset::Premiere.label()
        ));
        for spec in ACTIONS.iter().filter(|a| a.group == group) {
            out.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                spec.label,
                cell(spec.chukcut),
                cell(spec.capcut),
                cell(spec.premiere)
            ));
        }
    }
    out.push('\n');
    out.push_str(END);
    out
}

#[test]
fn the_manual_lists_every_shortcut_of_the_registry() {
    let path = manual();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let start = text
        .find(BEGIN)
        .unwrap_or_else(|| panic!("{} has no line {BEGIN}", path.display()));
    let end = text
        .find(END)
        .unwrap_or_else(|| panic!("{} has no line {END}", path.display()))
        + END.len();
    assert!(start < end, "the table markers are in the wrong order");

    let expected = table();
    let current = &text[start..end];
    if current == expected {
        return;
    }
    if std::env::var_os("CHUKCUT_BLESS").is_some() {
        let rewritten = format!("{}{}{}", &text[..start], expected, &text[end..]);
        std::fs::write(&path, rewritten)
            .unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
        return;
    }
    panic!(
        "docs/manual/shortcuts.md does not match the keymap registry. Run \
         `CHUKCUT_BLESS=1 cargo test -p chukcut-engine --test keymap_doc` and commit the \
         result.\n\nExpected table:\n{expected}"
    );
}

#[test]
fn every_action_has_a_row() {
    let table = table();
    for spec in ACTIONS {
        assert!(
            table.contains(&format!("| {} |", spec.label)),
            "{} has no row",
            spec.id
        );
    }
}
